### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/keyboard-backlightd#1]
# TODO before first release

* [x] Systemd unit
  - Systemd can load env from config, can that be put on command line?
* [x] Arch package
* [x] Ignore Caps Lock/Num lock/etc?

# Future improvements

## In this repo

* [ ] Man page, README.md is not accessible from installed package.
* [ ] Log format compatible with systemd
* [ ] Implement keep mode (´keep it locked for x-minutes).
* [ ] Drop root privileges once files are opened?

## Externally

* [x] When nix 0.27 is released, switch to new Epoll wrapper instead of our own copy of it.
